version: 2
jobs:
  build:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: Test and build
          command: |
            bash ./scripts/build.sh $CIRCLE_SHA1

      - store_artifacts:
          path: artifacts

      - persist_to_workspace:
          root: artifacts
          paths:
            - pal-tracker-*.tgz

  deployToReview:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
        environment:
          DEBIAN_FRONTEND: "noninteractive"
          EXTRACT_DEST: /tmp/extracted-archive
          ENVIRONMENT: review
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: Install CF CLI
          command: |
            apt-get update
            apt-get -y install apt-transport-https ca-certificates
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            apt-get update
            apt-get install cf-cli

      - run:
          name: Unzip artifacts
          command: |
            mkdir -p $EXTRACT_DEST
            tar -xvzf artifacts/pal-tracker-$CIRCLE_SHA1.tgz -C $EXTRACT_DEST

      - run:
          name: Deploy
          command: |
            cd $EXTRACT_DEST

            cf api $CF_API
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE_REVIEW"
            cf push -f manifest-$ENVIRONMENT.yml

  deployToProd:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
        environment:
          DEBIAN_FRONTEND: "noninteractive"
          EXTRACT_DEST: /tmp/extracted-archive
          ENVIRONMENT: production
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: Install CF CLI
          command: |
            apt-get update
            apt-get -y install apt-transport-https ca-certificates
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            apt-get update
            apt-get install cf-cli

      - run:
          name: Unzip artifacts
          command: |
            mkdir -p $EXTRACT_DEST
            tar -xvzf artifacts/pal-tracker-$CIRCLE_SHA1.tgz -C $EXTRACT_DEST

      - run:
          name: Deploy
          command: |
            cd $EXTRACT_DEST

            cf api $CF_API
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE_PROD"
            cf push -f manifest-$ENVIRONMENT.yml

workflows:
  version: 2
  deployment-pipeline:
    jobs:
      - build
      - deployToReview:
          requires:
          - build
      - canDeployToProduction:
          type: approval
          requires:
          - deployToReview
      - deployToProd:
          requires:
          - canDeployToProduction
